language: php
cache:
  apt: true
env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=4.1 WP_MULTISITE=0
  - WP_VERSION=4.1 WP_MULTISITE=1
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
matrix:
  include:
  - php: hhvm
    env: SKIP_XDEBUG_REMOVE=true; WP_VERSION=latest WP_MULTISITE=0
    sudo: required
    dist: trusty
    group: edge
    addons:
      apt:
        packages:
        - mysql-server-5.6
        - mysql-client-core-5.6
        - mysql-client-5.6
  exclude:
    - php: 5.3
      env: WP_VERSION=4.1 WP_MULTISITE=1
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 5.4
      env: WP_VERSION=4.1 WP_MULTISITE=1
    - php: 5.4
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 5.5
      env: WP_VERSION=4.1 WP_MULTISITE=1
    - php: 5.5
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.1
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: 7.1
      env: WP_VERSION=4.1 WP_MULTISITE=1
    - php: 7.0
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=4.1 WP_MULTISITE=1
    - php: hhvm
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: hhvm
      env: WP_VERSION=4.1 WP_MULTISITE=1
  allow_failures:
  - php: hhvm
  fast_finish: true
before_install:
   - |
      if [[ "$SKIP_XDEBUG_REMOVE" != "true" ]]; then
        phpenv config-rm xdebug.ini
        echo "xdebug removed";
      fi
before_script:
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - mysql --version
  - phpenv versions
script: cd tests; phpunit;
notifications:
  slack:
    rooms:
      secure: e2xmbwOoagh/rZIqUnx15HcTv5hZGxykvg8Tj0ENGi/bLcXgrEYxs2hpW+nzGggmSl22Eh+6wLRo62L0dEIIo1n+yknqDdAbVG7lmnX7Tc45JNgxWtSmAPzC3wAp0e9w1hy8HILPjYLxl0G7eXUvo3mKVRCCyD/Cyz5dDicE8tQ=
    on_success: change
    on_failure: always
    on_start: always
